//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsGestionCommandes.dao.ado.net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterEntities : DbContext
    {
        public MasterEntities()
            : base("name=MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<commande> commandes { get; set; }
        public virtual DbSet<livraison> livraisons { get; set; }
        public virtual DbSet<paiement> paiements { get; set; }
        public virtual DbSet<produit> produits { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<users_gc> users_gc { get; set; }
    }
}
