//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsGestionCommandes.dao.ado.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_gc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users_gc()
        {
            this.commandes = new HashSet<commande>();
            this.livraisons = new HashSet<livraison>();
        }
    
        public int ID { get; set; }
        public string nom_complet { get; set; }
        public Nullable<int> role_user { get; set; }
        public string login_user { get; set; }
        public string pwd_user { get; set; }
        public string phone { get; set; }
        public string adresse { get; set; }
        public string solde_compte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande> commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraison> livraisons { get; set; }
        public virtual role role { get; set; }
        override
        public string ToString()
        {
            return nom_complet;
        }
    }
}
